spring:
  application:
    name: hubs

  datasource:
    url: jdbc:mysql://localhost:3306/boards
    username: root
    password: ss0920
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format: true

  sql:
    init:
      mode: always