spring:
  application:
    name: Herbs

  datasource:
    url: jdbc:mysql://localhost:3306/mysql-container
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format: true

  sql:
    init:
      mode: always